# Changes here will be overwritten by Copier
_commit: v6.2.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: annika.bessing@eccenca.com
author_name: Annika Bessing
github_page: ''
project_description: Convert prices between currencies.
project_slug: currencies
pypi: false

