# Changes here will be overwritten by Copier
_commit: v6.3.1
_src_path: gh:eccenca/cmem-plugin-template
author_mail: annikabessing@yahoo.de
author_name: Annika Bessing
github_page: https://github.com/eccenca/cmem-plugin-currencies
project_description: Convert prices between currencies.
project_slug: currencies
pypi: true

